# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Number 21' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'PureLayout'

  # Pods for Number 21

end
